language: php

php: 
 - 7.1

before_script:
 - cp .env.travis .env
 - composer self-update
 - composer install --no-interaction


script:
 - php artisan key:generate
 - touch database/database.sqlite
 - php artisan migrate
 - vendor/bin/phpunit