version: '3'
services:
  server:
    build:
      context: ./
    container_name: 'redflag'
    restart: 'always'
    tty: 'true'
    stdin_open: 'true'
    ports:
      - "8080:80"
    volumes:
     - ./:/var/www/html/

  composer:
    restart: 'no'
    image: composer
    command: install --ignore-platform-reqs
    volumes:
      - .:/app